/*Users constants*/
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

/*Weeks constants*/
export const FETCH_WEEKS_REQUEST = 'FETCH_WEEKS_REQUEST';
export const FETCH_WEEKS_SUCCESS = 'FETCH_WEEKS_SUCCESS';

/*weeks approve or deny*/
export const PROCESSED_WEEK_REQUEST = 'PROCESSED_WEEK_REQUEST';
export const PROCESSED_WEEK_SUCCESS = 'PROCESSED_WEEK_SUCCESS';
